# Generated by Django 5.2 on 2025-04-29 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_client_connectgroup_proyect'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyect',
            name='client',
        ),
        migrations.DeleteModel(
            name='ConnectGroup',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='Proyect',
        ),
    ]
