# Generated by Django 5.2 on 2025-04-29 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_client_proyect_connectgroup_client_proyect'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connectgroup',
            name='connect_group_client',
        ),
        migrations.RemoveField(
            model_name='connectgroup',
            name='proyect',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='ConnectGroup',
        ),
        migrations.DeleteModel(
            name='Proyect',
        ),
    ]
