# Generated by Django 5.2 on 2025-04-29 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_connectgroup_connect_group_client_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proyect_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cg_part_number', models.CharField(max_length=100, unique=True)),
                ('client_part_number', models.CharField(max_length=50, unique=True)),
                ('client_name', models.CharField(max_length=100, unique=True)),
                ('proyect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='base.proyect')),
            ],
        ),
    ]
