# Generated by Django 5.2 on 2025-04-30 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_client_proyect_remove_request_customer_pn_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='proyect',
        ),
        migrations.RemoveField(
            model_name='request',
            name='client',
        ),
        migrations.AddField(
            model_name='request',
            name='customer_pn',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='ikor_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.DeleteModel(
            name='Proyect',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
