# Generated by Django 5.2 on 2025-04-30 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_remove_client_proyect_remove_request_client_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ikor_number', models.CharField(max_length=50, unique=True, verbose_name='Número de Parte Ikor')),
                ('customer_pn', models.CharField(max_length=100, verbose_name='Número de Parte del Cliente')),
                ('nickname', models.CharField(blank=True, max_length=100, null=True, verbose_name='Apodo')),
                ('project', models.CharField(blank=True, max_length=100, null=True, verbose_name='Proyecto')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Número de Parte',
                'verbose_name_plural': 'Números de Parte',
                'ordering': ['ikor_number'],
            },
        ),
        migrations.RemoveField(
            model_name='request',
            name='customer_pn',
        ),
        migrations.RemoveField(
            model_name='request',
            name='ikor_number',
        ),
        migrations.AddField(
            model_name='request',
            name='part_number',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='base.partnumber'),
        ),
    ]
