# Generated by Django 5.2 on 2025-05-02 18:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_partnumber_remove_request_customer_pn_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='request',
            name='approved_date',
        ),
        migrations.RemoveField(
            model_name='request',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='request',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='request',
            name='request_date',
        ),
        migrations.RemoveField(
            model_name='request',
            name='requirement_date',
        ),
        migrations.RemoveField(
            model_name='request',
            name='status',
        ),
        migrations.AddField(
            model_name='request',
            name='ref_client',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='line',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_code', models.CharField(blank=True, max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('requirement_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('PREPARATION', 'Preparation'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled'), ('On HOLD', 'On Hold'), ('DELIVERED', 'Delivered')], default='PENDING', max_length=12)),
                ('comment', models.TextField(blank=True, null=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_shipments', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_shipments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
