# Generated by Django 5.2 on 2025-05-02 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_remove_request_approved_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='shipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='base.shipment'),
        ),
    ]
