# Generated by Django 5.2 on 2025-05-09 14:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_alter_shipment_cancelled_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='confirmed_by',
        ),
        migrations.AlterField(
            model_name='shipment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_shipments', to=settings.AUTH_USER_MODEL),
        ),
    ]
