# Generated by Django 5.2 on 2025-05-09 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_remove_shipment_confirmed_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_shipments', to=settings.AUTH_USER_MODEL),
        ),
    ]
