# Generated by Django 5.2 on 2025-06-13 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_transport_shipment_transport'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='albaran',
            field=models.TextField(blank=True, null=True),
        ),
    ]
