# Generated by Django 5.2 on 2025-06-24 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_shipment_albaran'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='admin_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='wh_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
