# Generated by Django 5.2 on 2025-07-01 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_shipment_admin_comment_shipment_wh_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('PLANNER', 'Planner'), ('WAREHOUSE', 'Warehouse'), ('QUALITY', 'Quality')], max_length=15),
        ),
    ]
