# Generated by Django 5.2 on 2025-07-15 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_location_palletscan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='is_occupied',
        ),
    ]
