# Generated by Django 5.2 on 2025-07-15 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_remove_location_is_occupied'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='code',
            new_name='code_location',
        ),
    ]
