# Generated by Django 5.2 on 2025-07-16 21:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_rename_code_location_code_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='PalletHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('project', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('batch', models.CharField(max_length=50)),
                ('box_id', models.CharField(max_length=50)),
                ('mfg_part_number', models.CharField(max_length=50)),
                ('timestamp_in', models.DateTimeField()),
                ('timestamp_out', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.location')),
                ('user_in', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_pallets', to=settings.AUTH_USER_MODEL)),
                ('user_out', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='removed_pallets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
