# Generated by Django 5.2 on 2025-07-25 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_pallethistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_cli', models.CharField(max_length=20)),
                ('project', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_code', models.CharField(max_length=20)),
                ('fam_description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('number', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TypeIncoming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_art', models.CharField(max_length=20)),
                ('type_description', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='IncommingPartNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_pn', models.CharField(max_length=50)),
                ('supplier_pn', models.CharField(max_length=50)),
                ('family_inc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.family')),
                ('project_inc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.client')),
                ('supplier_inc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.supplier')),
                ('type_inc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.typeincoming')),
            ],
        ),
    ]
