# Generated by Django 5.2 on 2025-07-25 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_client_family_supplier_typeincoming_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='family',
            old_name='internal_code',
            new_name='incoming_customer_pn',
        ),
    ]
