# Generated by Django 5.2 on 2025-07-25 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_rename_internal_code_family_incoming_customer_pn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incommingpartnumber',
            name='supplier_inc',
        ),
        migrations.DeleteModel(
            name='Supplier',
        ),
    ]
