# Generated by Django 5.2 on 2025-07-28 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_remove_incommingpartnumber_supplier_inc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incommingpartnumber',
            name='project_inc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.client'),
        ),
        migrations.AlterField(
            model_name='incommingpartnumber',
            name='type_inc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.typeincoming'),
        ),
    ]
