# Generated by Django 5.2 on 2025-07-28 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0030_alter_incommingpartnumber_project_inc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incommingpartnumber',
            name='des_art',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
