# Generated by Django 5.2 on 2025-07-30 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0031_incommingpartnumber_des_art'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomingPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('fam', models.CharField(max_length=50)),
                ('descrip', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SupplierInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier', models.CharField(max_length=200)),
                ('value', models.CharField(blank=True, max_length=200, null=True)),
                ('order', models.PositiveIntegerField()),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='base.incomingpart')),
            ],
        ),
    ]
