# Generated by Django 5.2 on 2025-07-30 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0032_incomingpart_supplierinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incommingpartnumber',
            name='project_inc',
        ),
        migrations.RemoveField(
            model_name='incommingpartnumber',
            name='family_inc',
        ),
        migrations.RemoveField(
            model_name='incommingpartnumber',
            name='type_inc',
        ),
        migrations.AddField(
            model_name='incomingpart',
            name='is_urgent',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='Family',
        ),
        migrations.DeleteModel(
            name='IncommingPartNumber',
        ),
        migrations.DeleteModel(
            name='TypeIncoming',
        ),
    ]
