# Generated by Django 5.2 on 2025-08-07 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0034_cone_materialentry_cone_assigned_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialentry',
            name='is_urgent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='materialentry',
            name='supplier_company',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
