# Generated by Django 5.2 on 2025-08-08 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0035_materialentry_is_urgent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialentry',
            name='arrived_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='materialentry',
            name='date_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='materialentry',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='materialentry',
            name='is_label_attached',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='materialentry',
            name='is_pn_ok',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='materialentry',
            name='is_pn_supp_ok',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='materialentry',
            name='is_qty_ok',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='materialentry',
            name='measures',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='materialentry',
            name='order',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='materialentry',
            name='parcel_service',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='materialentry',
            name='physical_state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='materialentry',
            name='request_guide',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='materialentry',
            name='validated_labels',
            field=models.BooleanField(default=False),
        ),
    ]
