# Generated by Django 5.2 on 2025-08-11 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0036_materialentry_arrived_date_materialentry_date_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('PLANNER', 'Planner'), ('WAREHOUSE', 'Warehouse'), ('QUALITY', 'Quality'), ('BUYER', 'Buyer')], max_length=15),
        ),
    ]
