# Generated by Django 5.2 on 2025-08-11 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0037_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialentry',
            name='validation_quality_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
