# Generated by Django 5.2 on 2025-08-11 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0038_materialentry_validation_quality_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialentry',
            name='current_step',
            field=models.IntegerField(choices=[(0, 'Ingreso'), (1, 'Validación Material'), (2, 'Validación Calidad'), (3, 'Liberado'), (4, 'Finalizado')], default=0),
        ),
    ]
