# Generated by Django 5.2 on 2025-08-12 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0039_materialentry_current_step'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialentry',
            name='validation_quality_at',
        ),
    ]
