# Generated by Django 5.2 on 2025-08-12 21:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0040_remove_materialentry_validation_quality_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialentry',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incoming_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_code', models.CharField(max_length=20, null=True)),
                ('batch', models.CharField(max_length=20, null=True)),
                ('qty', models.CharField(max_length=20, null=True)),
                ('entry_date', models.DateTimeField(auto_now_add=True)),
                ('user_out_material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='removed_material', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
