# Generated by Django 5.2 on 2025-08-15 15:19

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0041_materialentry_created_by_withdrawal'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialWithdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_code', models.CharField(max_length=20, null=True)),
                ('batch', models.CharField(max_length=20, null=True)),
                ('qty', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad')),
                ('entry_date', models.DateTimeField(auto_now_add=True)),
                ('user_out_material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_withdrawals_removed', to=settings.AUTH_USER_MODEL)),
                ('production_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_withdrawals', to='base.productionorder')),
            ],
        ),
    ]
