# Generated by Django 5.2 on 2025-08-15 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0042_productionorder_materialwithdrawal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialwithdrawal',
            name='entry_date',
        ),
        migrations.AddField(
            model_name='productionorder',
            name='entry_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
