# Generated by Django 5.2 on 2025-08-19 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0043_remove_materialwithdrawal_entry_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialentry',
            name='material_validation',
            field=models.DateField(blank=True, null=True),
        ),
    ]
