# Generated by Django 5.2 on 2025-08-19 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0044_materialentry_material_validation'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialentry',
            name='document_validation',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
