# Generated by Django 5.2 on 2025-08-19 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0045_materialentry_document_validation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialentry',
            name='material_validation',
        ),
    ]
