# Generated by Django 5.2 on 2025-08-19 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0046_remove_materialentry_material_validation'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialentry',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
