# Generated by Django 5.2 on 2025-08-25 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0047_materialentry_delivered_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Withdrawal',
        ),
    ]
