# Generated by Django 5.2 on 2025-08-27 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0048_delete_withdrawal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialentry',
            name='physical_state',
        ),
        migrations.AddField(
            model_name='materialentry',
            name='packing_status',
            field=models.CharField(default=False),
        ),
        migrations.AddField(
            model_name='materialentry',
            name='quality_certified',
            field=models.CharField(default=False),
        ),
        migrations.AddField(
            model_name='materialentry',
            name='special_characteristics',
            field=models.CharField(default=False),
        ),
    ]
