# Generated by Django 5.2 on 2025-08-27 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0049_remove_materialentry_physical_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialentry',
            name='packing_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='materialentry',
            name='quality_certified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='materialentry',
            name='special_characteristics',
            field=models.BooleanField(default=False),
        ),
    ]
