# Generated by Django 5.2 on 2025-08-28 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0050_alter_materialentry_packing_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialentry',
            name='arrived_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
