# Generated by Django 5.2 on 2025-09-04 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0051_alter_materialentry_arrived_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialentry',
            name='current_step',
            field=models.IntegerField(choices=[(0, 'Ingreso'), (1, 'Validación Material'), (2, 'Validación Calidad'), (3, 'Liberado'), (4, 'Finalizado'), (5, 'Detenido'), (6, 'Rechazado')], default=0),
        ),
    ]
