# Generated by Django 5.2 on 2025-09-08 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0052_alter_materialentry_current_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialentry',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='materialentry',
            name='income',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='materialentry',
            name='rma',
            field=models.BooleanField(default=False),
        ),
    ]
