# Generated by Django 5.2 on 2025-09-08 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0053_materialentry_comments_materialentry_income_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialentry',
            name='removed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
