# Generated by Django 5.2 on 2025-09-08 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0054_materialentry_removed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialentry',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
