# Generated by Django 5.2 on 2025-09-11 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0055_materialentry_is_rejected'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialentry',
            name='previous_step',
            field=models.CharField(blank=True, choices=[(0, 'Ingreso'), (1, 'Validación Material'), (2, 'Validación Calidad'), (3, 'Liberado'), (4, 'Finalizado'), (5, 'Detenido'), (6, 'Rechazado')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='materialentry',
            name='current_step',
            field=models.CharField(choices=[(0, 'Ingreso'), (1, 'Validación Material'), (2, 'Validación Calidad'), (3, 'Liberado'), (4, 'Finalizado'), (5, 'Detenido'), (6, 'Rechazado')], default=1, max_length=50),
        ),
    ]
