# Generated by Django 5.2 on 2025-09-19 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0057_alter_materialentry_current_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialentry',
            name='is_expired',
            field=models.BooleanField(default=True),
        ),
    ]
