# Generated by Django 5.2 on 2025-09-19 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0058_materialentry_is_expired'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialentry',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
    ]
