# Generated by Django 5.2 on 2025-11-13 17:16

import base.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0059_alter_materialentry_is_expired'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Auditory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(editable=False, max_length=20, unique=True)),
                ('task', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('evidence', models.ImageField(blank=True, null=True, upload_to=base.models.upload_path_evidence)),
                ('action', models.CharField(blank=True, max_length=100, null=True)),
                ('action_evidence', models.ImageField(blank=True, null=True, upload_to=base.models.upload_path_evidence)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('DONE', 'Done')], default='PENDING', max_length=20)),
                ('assigned_to', models.ManyToManyField(limit_choices_to={'role': 'WAREHOUSE'}, related_name='auditories_assigned', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditories_created', to=settings.AUTH_USER_MODEL)),
                ('area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditories', to='base.warehousearea')),
            ],
        ),
    ]
