# Generated by Django 5.2 on 2025-11-13 19:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0060_warehousearea_auditory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditory',
            name='assigned_to',
        ),
        migrations.AddField(
            model_name='auditory',
            name='assigned_to',
            field=models.ForeignKey(limit_choices_to={'role': 'WAREHOUSE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditories_assigned', to=settings.AUTH_USER_MODEL),
        ),
    ]
