# Generated by Django 5.2 on 2025-11-19 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0061_remove_auditory_assigned_to_auditory_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialentry',
            name='folio',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='materialentry',
            name='folio_type',
            field=models.CharField(choices=[('INC', 'Incoming Material'), ('BUY', 'Buyer Request')], default='INC', max_length=10),
        ),
    ]
