# Generated by Django 5.2 on 2025-11-26 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0063_materialentry_received_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialentry',
            name='area',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='materialentry',
            name='located_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='materialentry',
            name='location',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='materialentry',
            name='current_step',
            field=models.IntegerField(choices=[(0, 'Ingreso'), (1, 'Validación Material'), (2, 'Validación Calidad'), (3, 'Liberado'), (4, 'Finalizado'), (5, 'Detenido'), (6, 'Rechazado'), (7, 'Ubicado')], default=0),
        ),
        migrations.AlterField(
            model_name='materialentry',
            name='previous_step',
            field=models.CharField(blank=True, choices=[(0, 'Ingreso'), (1, 'Validación Material'), (2, 'Validación Calidad'), (3, 'Liberado'), (4, 'Finalizado'), (5, 'Detenido'), (6, 'Rechazado'), (7, 'Ubicado')], max_length=50, null=True),
        ),
    ]
