# Generated by Django 5.2 on 2025-11-28 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0064_materialentry_area_materialentry_located_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditory',
            name='scheduled_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
