# Generated by Django 5.2 on 2025-11-28 19:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0065_auditory_scheduled_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditory',
            name='assigned_to',
        ),
        migrations.AddField(
            model_name='auditory',
            name='assigned_to',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'WAREHOUSE'}, related_name='auditories_assigned', to=settings.AUTH_USER_MODEL),
        ),
    ]
