# Generated by Django 5.2 on 2025-12-03 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0066_remove_auditory_assigned_to_auditory_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditory',
            name='in_progress_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
