# Generated by Django 5.2 on 2025-12-09 21:24

import base.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0067_auditory_in_progress_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditory',
            name='evidence',
        ),
        migrations.CreateModel(
            name='AuditoryEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=base.models.upload_path_evidence)),
                ('auditory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='base.auditory')),
            ],
        ),
    ]
