# Generated by Django 5.2 on 2025-12-15 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0068_remove_auditory_evidence_auditoryevidence'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialentry',
            name='esplanade',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
